# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matrixPowerWrap <- function(matA, power) {
    .Call('_mes_matrixPowerWrap', PACKAGE = 'mes', matA, power)
}

mesFitterWrap <- function(matVt, matWt, matF, vecG, lagsModelAll, Etype, Ttype, Stype, componentsNumber, componentsNumberSeasonal, yInSample, ot, backcasting) {
    .Call('_mes_mesFitterWrap', PACKAGE = 'mes', matVt, matWt, matF, vecG, lagsModelAll, Etype, Ttype, Stype, componentsNumber, componentsNumberSeasonal, yInSample, ot, backcasting)
}

mesForecasterWrap <- function(matVt, matWt, matF, lagsModelAll, Etype, Ttype, Stype, componentsNumber, componentsNumberSeasonal, h) {
    .Call('_mes_mesForecasterWrap', PACKAGE = 'mes', matVt, matWt, matF, lagsModelAll, Etype, Ttype, Stype, componentsNumber, componentsNumberSeasonal, h)
}

mesErrorerWrap <- function(matVt, matWt, matF, lagsModelAll, Etype, Ttype, Stype, componentsNumber, componentsNumberSeasonal, h, yInSample, ot) {
    .Call('_mes_mesErrorerWrap', PACKAGE = 'mes', matVt, matWt, matF, lagsModelAll, Etype, Ttype, Stype, componentsNumber, componentsNumberSeasonal, h, yInSample, ot)
}

mesSimulatorwrap <- function(arrVt, matErrors, matOt, matF, matWt, matG, Etype, Ttype, Stype, lagsModelAll, componentsNumberSeasonal, componentsNumber) {
    .Call('_mes_mesSimulatorwrap', PACKAGE = 'mes', arrVt, matErrors, matOt, matF, matWt, matG, Etype, Ttype, Stype, lagsModelAll, componentsNumberSeasonal, componentsNumber)
}

